version: '3.8'

services:
  konsilo-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: konsilo-website
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
